# Generated by Django 6.0.3 on 2026-06-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
